UI: Adds dark mode image for master slot empty state
jhuopensource/semesterly pull request #1111
Opened 2024-04-06 22:13 UTC by zydtiger

## Description
Adds a dark mode image for when the master course slot is empty. Makes it more coherent with dark mode UI.

## Change Log
### Before
![image](https://github.com/jhuopensource/semesterly/assets/43339228/5a758736-7974-4f56-942c-086eecac469c)
### After
![image](https://github.com/jhuopensource/semesterly/assets/43339228/0e668336-9036-4305-a1ee-9f202b2a85e8)

2024-04-06 22:14 UTC, zydtiger commented
I think my vscode formatter reformatted the file. The only line I changed was this:
![image](https://github.com/jhuopensource/semesterly/assets/43339228/cd81242e-67fd-4649-b603-6374a6f0cb00)

2024-04-06 23:53 UTC, JiaqiWang18 requested changes
The linter CI failed, could you check the format of `SideBar.tsx`

2024-04-07 00:00 UTC, JiaqiWang18 commented
> I think my vscode formatter reformatted the file. The only line I changed was this: ![image](https://private-user-images.githubusercontent.com/43339228/320236977-cd81242e-67fd-4649-b603-6374a6f0cb00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NDgyNDAsIm5iZiI6MTcxMjQ0Nzk0MCwicGF0aCI6Ii80MzMzOTIyOC8zMjAyMzY5NzctY2Q4MTI0MmUtNjdmZC00NjQ5LWI2MDMtNjM3NGE2ZjBjYjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDIzNTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYWMyMzE3Y2E1MzNhZTEwNWRiODQ5ODhiYTQ2ZjA3OTQyYWFkMjExMzE2NjViNjMzZmNhN2E3YTE1OGI2ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5E-z7K_d5EChcWRCw5InrQroklLX0yrUt-JuqIhxyBM)



That's fine because we want the format to be consistent with rest of the codebase but `TSLint` checks failed so there are more format issues that need to be fixed

2024-04-07 21:21 UTC, JiaqiWang18 approved these changes

2024-04-07 21:21 UTC, merged