Advising Backend
jhuopensource/semesterly pull request #184
Opened 2021-04-10 08:21 UTC by rbiz4

2021-04-10 17:12 UTC, miaboloix requested changes

2021-04-10 17:12 UTC, miaboloix commented on advising/views.py
> +    """ Handles the accessing of invited user timetables. """
no class body?

2021-04-10 17:12 UTC, miaboloix commented on advising/views.py
> +            status=status.HTTP_200_OK)
this doesn't grab any transcripts the user owns right? ONLY invited, right?

2021-04-10 18:09 UTC, JJamesWWang commented
Sorry I'm kind of out of the loop for this - what's the purpose of these views? Doesn't ForumView provide the same functionality of these new views?

2021-04-13 16:45 UTC, miaboloix commented
can we confirm whether this functionality is new or not?

2021-04-13 18:57 UTC, closed without merging