Invite advisors modal
jhuopensource/semesterly pull request #218
Opened 2021-04-14 06:11 UTC by jwfung

Creating this modal:
![image](https://user-images.githubusercontent.com/59128478/114662378-95771880-9cc6-11eb-803a-c75aec645996.png)

I messed up the last branch with the merge so hopefully this one should be good

2021-04-14 15:33 UTC, miaboloix commented on static/js/redux/ui/advisor_menu.jsx
> +    const advisorList = (this.props.advisors.length > 0) ?
When you aren't on any particular semester (aka when selected_semester = null) the list of advisors still shows up above the forum.

2021-04-14 15:35 UTC, miaboloix commented
there are lint errors - please fix them :)

2021-04-14 15:42 UTC, miaboloix requested changes
some of the lint errors might resolve themselves by pulling the most recent cs310-spring21 branch

2021-04-14 15:42 UTC, miaboloix commented on static/js/redux/ui/advisor_menu.jsx
> +    const advisorList = (this.props.advisors.length > 0) ?
you can pass this `selected_semester` as a prop and then check that if it is null, we don't display the list. Something like that.

2021-04-14 15:42 UTC, miaboloix commented on static/js/redux/ui/advisor_menu.jsx
> +    const advisorList = (this.props.advisors.length > 0) ?
this list is also consistent if you switch semesters - but i think in the backend it is semester-based. So, if you add an advisor to one semester, you aren't adding them to all of your transcripts. Not sure.

2021-04-14 15:42 UTC, miaboloix commented on static/js/redux/ui/comment_forum.jsx
> +        //TODO: Set this to list of student's advisors from SIS
Create an issue for this so we can track it. This would involve a fetch() to get the data from the backend (a list of the student's advisors)

2021-04-14 15:42 UTC, miaboloix commented on static/js/redux/ui/comment_forum.jsx
> +            semester_name={semester_name}
use `selected_semester` here and then parse inside the component :) i believe this will be empty.

2021-04-14 21:01 UTC, miaboloix commented
Fixed lint errors

2021-04-14 21:02 UTC, miaboloix commented
Also moved the function that does the adding/removing to `advising.jsx` because we want to keep a single transcript state!

2021-04-15 16:56 UTC, miaboloix approved these changes

2021-04-15 17:49 UTC, rbiz4 approved these changes

2021-04-15 18:15 UTC, merged