Add More Semesters for cs310 dev site
jhuopensource/semesterly pull request #251
Opened 2021-04-20 15:42 UTC by Boccca2014

Closes #250

2021-04-20 16:28 UTC, miaboloix requested changes

2021-04-20 16:28 UTC, miaboloix commented on build/run_parser.sh
you can use one line to ingest multiple semesters ex: `/usr/bin/python manage.py ingest jhu --terms Spring Fall --years 2019 2020;`

2021-04-20 21:16 UTC, JJamesWWang approved these changes

2021-04-21 15:22 UTC, miaboloix approved these changes

2021-04-21 15:22 UTC, merged