Create New Timetable When Creating Custom Event
jhuopensource/semesterly pull request #717
Opened 2022-03-12 21:57 UTC by JiaqiWang18

## Description
Add code to create a new timetable on creating custom events when the user does not have any timetable

2022-03-14 05:34 UTC, JJamesWWang requested changes
For some reason, isFetching in timetablesReducer is not being set to False, so the circle in the top right is infinitely spinning. Looking into this right now.

2022-03-14 05:36 UTC, JJamesWWang commented
Also, I just realized that we were planning to be remove personal events from the body of the saving timetable request, so might be better to find a different solution here

2022-03-14 05:38 UTC, JJamesWWang commented
I think it might be better to leave that to a different PR though, so unless you say otherwise, let's just try to fix the fetching issue.

2022-03-14 05:38 UTC, JiaqiWang18 commented
Sure, I will look onto a different solution tomorrow

On Mon, Mar 14, 2022, 1:37 AM James S. Wang ***@***.***>
wrote:

> Also, I just realized that we were planning to be remove personal events
> from the body of the saving timetable request, so might be better to find a
> different solution here
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jhuopensource/semesterly/pull/717#issuecomment-1066400655>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI6BZPA2LAI42WM3KORLG3LU73NBFANCNFSM5QSNTGSA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-03-14 05:39 UTC, JiaqiWang18 commented
> I think it might be better to leave that to a different PR though, so unless you say otherwise, let's just try to fix the fetching issue.

This is fine as well

2022-03-14 05:55 UTC, JJamesWWang commented
There's a deeper issue with the codebase here imo. I wonder if we can combine the two timetable endpoints (/timetables) and (/user/timetables) into one. Or at least separate them so that only one is called at a time because this `isFetching` is only spinning because there's no timetables returned (as the only thing they added is a custom event). To be honest, `fetchTimetables` probably should never have been called to begin with.

2022-03-14 05:57 UTC, JJamesWWang commented
A temporary fix I can think of is to add a new reducer that sets `isFetching` to False and extend the if chain in `timetable_actions.jsx`, line 112 with an else. I'll let you also look into it to see what you come up with.

2022-03-14 18:43 UTC, JiaqiWang18 commented
> A temporary fix I can think of is to add a new reducer that sets `isFetching` to False and extend the if chain in `timetable_actions.jsx`, line 112 with an else. I'll let you also look into it to see what you come up with.

Adding an action to set it to false seems to be the best fix without tackling the deeper issue

2022-03-14 19:03 UTC, JJamesWWang commented
I think we can ahead with that implementation then

2022-03-14 19:45 UTC, JJamesWWang reviewed
We can probably replace the fetchingCourses reducer that only sets isFetching to true as well
Line 56 in timetablesSlice.ts

2022-03-15 05:12 UTC, JJamesWWang approved these changes
Looks good

2022-03-15 05:12 UTC, JJamesWWang commented on static/js/redux/actions/timetable_actions.jsx
>      // mark that we are now asynchronously requesting timetables
Looks good

2022-03-15 05:12 UTC, merged